"""WAF/IPS detection and evasion engine."""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field

from basilisk.encoding import EncodingEngine
from basilisk.models import Finding

logger = logging.getLogger(__name__)


@dataclass
class WAFSignature:
    name: str
    headers: dict[str, str] = field(default_factory=dict)
    status_codes: list[int] = field(default_factory=list)
    body_patterns: list[str] = field(default_factory=list)
    cookie_patterns: list[str] = field(default_factory=list)


# ── Known WAF fingerprints ────────────────────────────────────────────

WAF_SIGNATURES: list[WAFSignature] = [
    WAFSignature(
        name="Cloudflare",
        headers={"server": "cloudflare", "cf-ray": ""},
        body_patterns=["attention required! | cloudflare", "cloudflare ray id"],
        cookie_patterns=["__cfduid", "__cf_bm", "cf_clearance"],
    ),
    WAFSignature(
        name="AWS WAF",
        headers={"x-amzn-requestid": "", "x-amz-cf-id": ""},
        status_codes=[403],
        body_patterns=["request blocked", "aws waf"],
    ),
    WAFSignature(
        name="ModSecurity",
        headers={"server": "mod_security"},
        body_patterns=["mod_security", "modsecurity", "noyb"],
    ),
    WAFSignature(
        name="Akamai",
        headers={"x-akamai-transformed": ""},
        body_patterns=["access denied", "akamai"],
        cookie_patterns=["akamai"],
    ),
    WAFSignature(
        name="Imperva/Incapsula",
        headers={"x-cdn": "imperva", "x-iinfo": ""},
        body_patterns=["incapsula incident id", "powered by incapsula"],
        cookie_patterns=["visid_incap", "incap_ses"],
    ),
    WAFSignature(
        name="F5 BIG-IP ASM",
        headers={"x-wa-info": ""},
        body_patterns=["the requested url was rejected"],
        cookie_patterns=["ts", "bigipserver"],
    ),
    WAFSignature(
        name="Sucuri",
        headers={"x-sucuri-id": "", "server": "sucuri"},
        body_patterns=["sucuri website firewall", "access denied - sucuri"],
    ),
    WAFSignature(
        name="Barracuda",
        headers={"server": "barracuda"},
        body_patterns=["barracuda networks"],
        cookie_patterns=["barra_counter_session"],
    ),
    WAFSignature(
        name="Fortinet/FortiWeb",
        headers={"server": "fortiweb"},
        body_patterns=["fortigate", "fortiweb"],
        cookie_patterns=["cookiesession1"],
    ),
    WAFSignature(
        name="DDoS-Guard",
        headers={"server": "ddos-guard"},
        body_patterns=["ddos-guard"],
    ),
    WAFSignature(
        name="Wordfence",
        body_patterns=["generated by wordfence", "wfwaf-authcookie"],
    ),
    WAFSignature(
        name="Azure WAF",
        headers={"x-azure-ref": ""},
        body_patterns=["azure web application firewall"],
    ),
    WAFSignature(
        name="Google Cloud Armor",
        body_patterns=["google cloud armor"],
        status_codes=[403],
    ),
]


@dataclass
class WAFDetectionResult:
    detected: bool = False
    waf_name: str = ""
    confidence: float = 0.0
    evidence: list[str] = field(default_factory=list)


class WAFDetector:
    """Identify and fingerprint WAF/IPS systems."""

    def detect(self, response: dict) -> WAFDetectionResult:
        """Analyze a response to identify WAF presence."""
        headers = response.get("headers", {})
        body = response.get("body", "")
        status = response.get("status_code", 0)
        cookies_raw = headers.get("Set-Cookie", "")

        lower_headers = {k.lower(): v.lower() for k, v in headers.items()}
        lower_body = body.lower()

        best_match = WAFDetectionResult()

        for sig in WAF_SIGNATURES:
            score = 0.0
            evidence: list[str] = []

            # Check headers
            for hdr_key, hdr_val in sig.headers.items():
                if hdr_key in lower_headers:
                    if not hdr_val or hdr_val in lower_headers[hdr_key]:
                        score += 0.3
                        evidence.append(f"Header match: {hdr_key}")

            # Check body patterns
            for pattern in sig.body_patterns:
                if pattern in lower_body:
                    score += 0.3
                    evidence.append(f"Body pattern: {pattern[:40]}")

            # Check status codes
            if sig.status_codes and status in sig.status_codes:
                score += 0.15
                evidence.append(f"Status code: {status}")

            # Check cookies
            for cookie_pat in sig.cookie_patterns:
                if cookie_pat.lower() in cookies_raw.lower():
                    score += 0.2
                    evidence.append(f"Cookie pattern: {cookie_pat}")

            if score > best_match.confidence:
                best_match = WAFDetectionResult(
                    detected=True,
                    waf_name=sig.name,
                    confidence=min(score, 1.0),
                    evidence=evidence,
                )

        # Generic WAF detection (no specific fingerprint)
        if not best_match.detected:
            generic_signals = 0
            generic_evidence: list[str] = []

            if status in (403, 406, 429, 503):
                generic_signals += 1
                generic_evidence.append(f"Suspicious status: {status}")

            block_phrases = [
                "request blocked", "access denied", "forbidden",
                "not acceptable", "web application firewall",
                "security policy", "request rejected",
            ]
            for phrase in block_phrases:
                if phrase in lower_body:
                    generic_signals += 1
                    generic_evidence.append(f"Block phrase: {phrase}")

            if generic_signals >= 2:
                best_match = WAFDetectionResult(
                    detected=True,
                    waf_name="Unknown WAF",
                    confidence=0.4,
                    evidence=generic_evidence,
                )

        return best_match

    def probe(self, target_fn, base_url: str) -> WAFDetectionResult:
        """
        Actively probe for WAF by sending known-bad payloads.

        target_fn(url) -> response dict
        """
        probes = [
            f"{base_url}/?test=<script>alert(1)</script>",
            f"{base_url}/?id=1' OR '1'='1'--",
            f"{base_url}/?cmd=;cat /etc/passwd",
            f"{base_url}/?file=../../etc/passwd",
        ]

        for probe_url in probes:
            response = target_fn(probe_url)
            if response:
                result = self.detect(response)
                if result.detected:
                    return result

        return WAFDetectionResult()


class WAFEvasion:
    """Apply evasion transforms when a WAF is detected."""

    def __init__(self):
        self.encoder = EncodingEngine()
        self._strategies: dict[str, list] = {
            "Cloudflare": ["double_url", "unicode_norm", "case_rand", "chunk"],
            "AWS WAF": ["unicode_norm", "html_entity", "case_rand"],
            "ModSecurity": ["sql_comment", "case_rand", "double_url", "unicode"],
            "Akamai": ["double_url", "unicode_norm", "null_byte"],
            "Imperva/Incapsula": ["case_rand", "html_entity", "unicode_norm"],
            "F5 BIG-IP ASM": ["sql_comment", "double_url", "unicode"],
            "Sucuri": ["double_url", "unicode_norm", "case_rand"],
            "Wordfence": ["case_rand", "html_entity", "unicode_norm"],
        }

    def get_strategies(self, waf_name: str) -> list[str]:
        return self._strategies.get(waf_name, ["case_rand", "double_url", "unicode_norm"])

    def evade(self, payload: str, waf_name: str) -> list[str]:
        """
        Generate evasion variants of a payload for a specific WAF.
        Returns a list of variant payloads.
        """
        strategies = self.get_strategies(waf_name)
        variants: list[str] = [payload]

        strategy_map = {
            "double_url": self.encoder.double_url_encode,
            "unicode_norm": self.encoder.unicode_normalization_bypass,
            "case_rand": self.encoder.case_randomize,
            "html_entity": lambda p: self.encoder.html_entity_encode(p, numeric=True),
            "sql_comment": self.encoder.sql_comment_bypass,
            "unicode": self.encoder.unicode_encode,
            "null_byte": lambda p: p.replace(" ", "%00 "),
            "chunk": self.encoder.chunk_transfer_encode,
            "hex": self.encoder.hex_encode,
        }

        for strategy in strategies:
            fn = strategy_map.get(strategy)
            if fn:
                try:
                    variant = fn(payload)
                    if variant and variant not in variants:
                        variants.append(variant)
                except Exception:
                    continue

        return variants

    def auto_evade(self, payloads: list[str], waf_result: WAFDetectionResult) -> list[str]:
        """Apply evasion to all payloads based on detected WAF."""
        if not waf_result.detected:
            return payloads

        all_variants: list[str] = []
        for payload in payloads:
            variants = self.evade(payload, waf_result.waf_name)
            all_variants.extend(variants)

        return list(dict.fromkeys(all_variants))
