"""
Embedded single-page web UI for the Basilisk ephemeral session dashboard.
Includes code-based login screen, real-time metrics, animated findings list, log console, and auto-disconnect notice when session ends.
"""

def GET_DASHBOARD_HTML() -> str:
    return """<!DOCTYPE html>
<html lang="en" class="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Basilisk — Live Session Dashboard</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;600&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <script>
    tailwind.config = {
      darkMode: 'class',
      theme: {
        extend: {
          fontFamily: {
            sans: ['Inter', 'sans-serif'],
            mono: ['Fira Code', 'monospace'],
          },
          colors: {
            emerald: { 400: '#34d399', 500: '#10b981', 600: '#059669' },
            dark: { 900: '#0b0f19', 800: '#111827', 700: '#1f2937' }
          }
        }
      }
    }
  </script>
  <style>
    body { background-color: #0b0f19; color: #f3f4f6; }
    .glass { background: rgba(17, 24, 39, 0.7); backdrop-filter: blur(12px); border: 1px solid rgba(255, 255, 255, 0.08); }
    .glass-card { background: rgba(31, 41, 55, 0.4); border: 1px solid rgba(255, 255, 255, 0.05); }
    ::-webkit-scrollbar { width: 6px; height: 6px; }
    ::-webkit-scrollbar-track { background: #0b0f19; }
    ::-webkit-scrollbar-thumb { background: #374151; border-radius: 4px; }
    ::-webkit-scrollbar-thumb:hover { background: #4b5563; }
  </style>
</head>
<body class="font-sans antialiased min-h-screen flex flex-col selection:bg-emerald-500 selection:text-black">

  <!-- ==================== LOGIN VIEW ==================== -->
  <div id="login-view" class="fixed inset-0 z-50 flex items-center justify-center bg-dark-900 bg-opacity-95 backdrop-blur-md p-4">
    <div class="glass max-w-md w-full p-8 rounded-2xl shadow-2xl text-center relative overflow-hidden">
      <div class="absolute -top-24 -left-24 w-48 h-48 bg-emerald-500/20 rounded-full blur-3xl"></div>
      <div class="absolute -bottom-24 -right-24 w-48 h-48 bg-emerald-500/10 rounded-full blur-3xl"></div>

      <div class="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 mb-4 shadow-inner">
        <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/>
        </svg>
      </div>

      <h1 class="text-2xl font-bold tracking-tight text-white mb-1">BASILISK CLI</h1>
      <p class="text-sm text-gray-400 mb-6">Ephemeral Local Session Dashboard</p>

      <form id="login-form" onsubmit="handleLogin(event)" class="space-y-4">
        <div>
          <label for="passcode" class="block text-xs font-semibold uppercase tracking-wider text-gray-400 mb-2">Session Passcode</label>
          <input type="text" id="passcode" placeholder="BSK-XXXXXX" uppercase
            class="w-full px-4 py-3 rounded-xl bg-dark-800 border border-gray-700 text-center font-mono text-xl tracking-widest text-emerald-400 placeholder-gray-600 focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500 transition-all">
        </div>

        <div id="login-error" class="hidden text-xs text-red-400 bg-red-950/50 border border-red-800/50 rounded-lg p-2.5"></div>

        <button type="submit" class="w-full py-3.5 px-4 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-dark-900 font-semibold transition-all shadow-lg shadow-emerald-500/20 active:scale-[0.98]">
          Authenticate Session
        </button>
      </form>

      <p class="text-xs text-gray-500 mt-6 leading-relaxed">
        Passcode is generated by the Basilisk terminal process when starting a scan.
        This local session will self-destruct when the terminal closes.
      </p>
    </div>
  </div>

  <!-- ==================== DASHBOARD VIEW ==================== -->
  <div id="dashboard-view" class="hidden flex-1 flex flex-col">
    <!-- Header -->
    <header class="glass sticky top-0 z-40 px-6 py-4 flex items-center justify-between border-b border-gray-800">
      <div class="flex items-center gap-3">
        <div class="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"/>
          </svg>
        </div>
        <div>
          <div class="flex items-center gap-2">
            <h2 class="font-bold text-lg text-white">BASILISK</h2>
            <span id="session-badge" class="px-2 py-0.5 text-xs font-medium rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/30">
              Ephemeral Session
            </span>
          </div>
          <p id="target-display" class="text-xs text-gray-400 font-mono">Target: Loading...</p>
        </div>
      </div>

      <div class="flex items-center gap-3">
        <div class="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-dark-800 border border-gray-800 text-xs">
          <span class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
          <span id="status-text" class="text-gray-300 font-medium">Scanning...</span>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <main class="flex-1 max-w-7xl w-full mx-auto p-6 space-y-6">

      <!-- Status & Progress Banner -->
      <div id="progress-container" class="glass p-5 rounded-2xl border border-gray-800 space-y-3">
        <div class="flex justify-between items-center text-sm">
          <span id="progress-msg" class="text-gray-300 font-medium">Initializing audit engine...</span>
          <span id="progress-pct" class="text-xs font-mono text-emerald-400">Live Stream</span>
        </div>
        <div class="w-full bg-dark-800 rounded-full h-2 overflow-hidden p-0.5 border border-gray-800">
          <div id="progress-bar" class="bg-gradient-to-r from-emerald-500 to-teal-400 h-full rounded-full transition-all duration-300 w-1/4 animate-pulse"></div>
        </div>
      </div>

      <!-- Stats Grid -->
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div class="glass-card p-5 rounded-2xl border border-gray-800">
          <p class="text-xs font-medium text-gray-400 uppercase tracking-wider">Total Findings</p>
          <p id="stat-total" class="text-3xl font-bold text-white mt-1">0</p>
        </div>
        <div class="glass-card p-5 rounded-2xl border border-gray-800">
          <p class="text-xs font-medium text-red-400 uppercase tracking-wider">High / Critical</p>
          <p id="stat-high" class="text-3xl font-bold text-red-400 mt-1">0</p>
        </div>
        <div class="glass-card p-5 rounded-2xl border border-gray-800">
          <p class="text-xs font-medium text-gray-400 uppercase tracking-wider">Pages Scanned</p>
          <p id="stat-pages" class="text-3xl font-bold text-white mt-1">0</p>
        </div>
        <div class="glass-card p-5 rounded-2xl border border-gray-800">
          <p class="text-xs font-medium text-gray-400 uppercase tracking-wider">Forms Audited</p>
          <p id="stat-forms" class="text-3xl font-bold text-white mt-1">0</p>
        </div>
      </div>

      <!-- Findings Section -->
      <div class="glass rounded-2xl border border-gray-800 overflow-hidden">
        <div class="p-5 border-b border-gray-800 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div class="flex items-center gap-3">
            <h3 class="font-bold text-base text-white">Vulnerability Findings</h3>
            <span id="findings-count" class="px-2 py-0.5 text-xs font-mono rounded-md bg-dark-800 text-gray-400 border border-gray-700">0</span>
          </div>

          <!-- Controls -->
          <div class="flex items-center gap-3">
            <input type="text" id="search-input" oninput="renderFindings()" placeholder="Search findings..."
              class="px-3 py-1.5 text-xs rounded-lg bg-dark-800 border border-gray-700 text-gray-200 placeholder-gray-500 focus:outline-none focus:border-emerald-500">

            <select id="severity-filter" onchange="renderFindings()"
              class="px-3 py-1.5 text-xs rounded-lg bg-dark-800 border border-gray-700 text-gray-200 focus:outline-none focus:border-emerald-500">
              <option value="ALL">All Severities</option>
              <option value="Critical">Critical</option>
              <option value="High">High</option>
              <option value="Medium">Medium</option>
              <option value="Low">Low</option>
              <option value="Info">Info</option>
            </select>
          </div>
        </div>

        <!-- Table -->
        <div class="overflow-x-auto">
          <table class="w-full text-left text-xs text-gray-300">
            <thead class="bg-dark-800/80 text-gray-400 uppercase font-semibold border-b border-gray-800">
              <tr>
                <th class="px-5 py-3.5 w-28">Severity</th>
                <th class="px-5 py-3.5">Vulnerability</th>
                <th class="px-5 py-3.5">Target Endpoint</th>
                <th class="px-5 py-3.5">Description</th>
              </tr>
            </thead>
            <tbody id="findings-list" class="divide-y divide-gray-800/50">
              <tr>
                <td colspan="4" class="px-5 py-12 text-center text-gray-500">
                  No issues detected yet. Audit in progress...
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Live Log Stream -->
      <div class="glass rounded-2xl border border-gray-800 p-5 space-y-3">
        <h4 class="text-xs font-semibold uppercase tracking-wider text-gray-400">Terminal Activity Console</h4>
        <div id="log-console" class="h-36 overflow-y-auto font-mono text-xs text-gray-400 bg-dark-900/90 rounded-xl p-4 space-y-1 border border-gray-800/80">
          <div class="text-gray-600">[System] Initialized ephemeral dashboard observer.</div>
        </div>
      </div>

    </main>

    <footer class="text-center text-xs text-gray-600 py-6 border-t border-gray-800/50">
      Basilisk Standalone Local Security Scanner — Ephemeral session ends when CLI process exits.
    </footer>
  </div>

  <!-- Disconnected Banner -->
  <div id="disconnected-modal" class="hidden fixed inset-0 z-50 flex items-center justify-center bg-dark-900/90 backdrop-blur-md p-4">
    <div class="glass max-w-sm w-full p-6 rounded-2xl text-center space-y-4 border-red-500/30">
      <div class="w-12 h-12 rounded-full bg-red-500/10 border border-red-500/30 text-red-400 mx-auto flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"/>
        </svg>
      </div>
      <h3 class="text-lg font-bold text-white">CLI Session Terminated</h3>
      <p class="text-xs text-gray-400 leading-relaxed">
        The terminal process has ended or closed. As requested, this ephemeral dashboard session has expired and is now inactive.
      </p>
    </div>
  </div>

  <script>
    let sessionData = null;
    let pollInterval = null;

    // Check query params for code
    const urlParams = new URLSearchParams(window.location.search);
    const codeParam = urlParams.get('code');
    if (codeParam) {
      document.getElementById('passcode').value = codeParam;
      autoLogin(codeParam);
    }

    async function autoLogin(code) {
      try {
        const res = await fetch('/api/login', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ code })
        });
        const data = await res.json();
        if (data.success) {
          showDashboard();
        }
      } catch(e) {}
    }

    async function handleLogin(e) {
      e.preventDefault();
      const code = document.getElementById('passcode').value.trim();
      const errorDiv = document.getElementById('login-error');
      errorDiv.classList.add('hidden');

      try {
        const res = await fetch('/api/login', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ code })
        });
        const data = await res.json();
        if (data.success) {
          showDashboard();
        } else {
          errorDiv.innerText = data.error || 'Invalid passcode';
          errorDiv.classList.remove('hidden');
        }
      } catch(err) {
        errorDiv.innerText = 'Could not connect to local server';
        errorDiv.classList.remove('hidden');
      }
    }

    function showDashboard() {
      document.getElementById('login-view').classList.add('hidden');
      document.getElementById('dashboard-view').classList.remove('hidden');
      startPolling();
    }

    function startPolling() {
      fetchSession();
      pollInterval = setInterval(fetchSession, 1500);
    }

    async function fetchSession() {
      try {
        const res = await fetch('/api/session');
        if (res.status === 401) {
          // Token expired or invalid
          document.getElementById('login-view').classList.remove('hidden');
          document.getElementById('dashboard-view').classList.add('hidden');
          clearInterval(pollInterval);
          return;
        }
        if (!res.ok) throw new Error('Disconnected');

        sessionData = await res.json();
        updateUI();
      } catch(e) {
        // CLI server process exited!
        clearInterval(pollInterval);
        document.getElementById('disconnected-modal').classList.remove('hidden');
      }
    }

    function updateUI() {
      if (!sessionData) return;

      document.getElementById('target-display').innerText = 'Target: ' + sessionData.target_url;
      document.getElementById('status-text').innerText = sessionData.status.toUpperCase();
      document.getElementById('progress-msg').innerText = sessionData.progress_msg;

      if (sessionData.completed) {
        document.getElementById('progress-bar').classList.remove('animate-pulse');
        document.getElementById('progress-bar').style.width = '100%';
        document.getElementById('progress-pct').innerText = 'Scan Complete';
      }

      const findings = sessionData.findings || [];
      document.getElementById('stat-total').innerText = findings.length;
      document.getElementById('stat-pages').innerText = sessionData.pages_scanned || 0;
      document.getElementById('stat-forms').innerText = sessionData.forms_found || 0;

      const highCount = findings.filter(f => ['High', 'Critical'].includes(f.severity)).length;
      document.getElementById('stat-high').innerText = highCount;

      renderFindings();

      // Render log console
      const logBox = document.getElementById('log-console');
      if (sessionData.logs) {
        logBox.innerHTML = sessionData.logs.map(l => `<div>${escapeHtml(l)}</div>`).join('');
        logBox.scrollTop = logBox.scrollHeight;
      }
    }

    function renderFindings() {
      if (!sessionData) return;
      let findings = sessionData.findings || [];

      const search = document.getElementById('search-input').value.toLowerCase();
      const sev = document.getElementById('severity-filter').value;

      if (sev !== 'ALL') {
        findings = findings.filter(f => (f.severity || '').toLowerCase() === sev.toLowerCase());
      }
      if (search) {
        findings = findings.filter(f =>
          (f.vulnerability || '').toLowerCase().includes(search) ||
          (f.target || '').toLowerCase().includes(search) ||
          (f.description || '').toLowerCase().includes(search)
        );
      }

      document.getElementById('findings-count').innerText = findings.length;

      const tbody = document.getElementById('findings-list');
      if (findings.length === 0) {
        tbody.innerHTML = `<tr><td colspan="4" class="px-5 py-8 text-center text-gray-500">No matching issues flagged.</td></tr>`;
        return;
      }

      const sevColor = {
        'Critical': 'bg-red-950/80 text-red-400 border-red-800/60',
        'High': 'bg-red-900/50 text-red-400 border-red-800/40',
        'Medium': 'bg-yellow-950/80 text-yellow-400 border-yellow-800/60',
        'Low': 'bg-cyan-950/80 text-cyan-400 border-cyan-800/60',
        'Info': 'bg-gray-800 text-gray-400 border-gray-700'
      };

      tbody.innerHTML = findings.map(f => `
        <tr class="hover:bg-dark-800/40 transition-colors">
          <td class="px-5 py-4">
            <span class="px-2.5 py-1 text-[10px] font-semibold rounded-md border ${sevColor[f.severity] || sevColor['Info']}">
              ${f.severity || 'Info'}
            </span>
          </td>
          <td class="px-5 py-4 font-semibold text-white">${escapeHtml(f.vulnerability || 'Issue')}</td>
          <td class="px-5 py-4 font-mono text-gray-400 max-w-xs truncate">${escapeHtml(f.target || '')}</td>
          <td class="px-5 py-4 text-gray-300">${escapeHtml(f.description || '')}</td>
        </tr>
      `).join('');
    }

    function escapeHtml(str) {
      return (str || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    }
  </script>
</body>
</html>"""
